### ISSUE TITLE
用户注册 Internal Server Error

### ISSUE THREAD

**Issue by xmflswood** [zhangchunlin/f1do.com#1]
￼￼￼￼￼Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

另外项目代码没开源吗？

**Comment by zhangchunlin** [comment]
有空我修复一下

目前还没打算开源,将来有可能吧

**Comment by zhangchunlin** [comment]
修复了,是框架的问题,我提了个PR: https://github.com/limodou/uliweb-apps/pull/4
